# -------------- #
# global configs
# -------------- #

[global]
# List of rules to enable exclusively (replaces defaults).
enable = ["ALL"]
# Additional rules to disable on top of the disable list (additive)
extend-disable = ["MD033"]
# List of file/directory patterns to exclude from linting.
exclude = ["wt-webapp-sdk", "wt-rest-stubs"]

# ------------------ #
# rule level configs
# ------------------ #

[MD013]
code-blocks = false

[MD060]
style = "compact"

[MD063]
ignore-words = []
