/* tslint:disable */
/* eslint-disable */
/**
 * API for whisperpine/walkie-talkie project
 * API for whisperpine/walkie-talkie repository on GitHub
 *
 * The version of the OpenAPI document: 0.1.0-alpha
 * Contact: yusonglai64@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Channel
 */
export interface Channel {
    /**
     * 
     * @type {number}
     * @memberof Channel
     */
    channelId: number;
    /**
     * 
     * @type {string}
     * @memberof Channel
     */
    channelName?: string;
}

/**
 * Check if a given object implements the Channel interface.
 */
export function instanceOfChannel(value: object): value is Channel {
    if (!('channelId' in value) || value['channelId'] === undefined) return false;
    return true;
}

export function ChannelFromJSON(json: any): Channel {
    return ChannelFromJSONTyped(json, false);
}

export function ChannelFromJSONTyped(json: any, ignoreDiscriminator: boolean): Channel {
    if (json == null) {
        return json;
    }
    return {
        
        'channelId': json['channel_id'],
        'channelName': json['channel_name'] == null ? undefined : json['channel_name'],
    };
}

export function ChannelToJSON(json: any): Channel {
    return ChannelToJSONTyped(json, false);
}

export function ChannelToJSONTyped(value?: Channel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'channel_id': value['channelId'],
        'channel_name': value['channelName'],
    };
}

