/* tslint:disable */
/* eslint-disable */
/**
 * API for whisperpine/walkie-talkie project
 * API for whisperpine/walkie-talkie repository on GitHub
 *
 * The version of the OpenAPI document: 0.1.0-alpha
 * Contact: yusonglai64@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Channel,
} from '../models/index';
import {
    ChannelFromJSON,
    ChannelToJSON,
} from '../models/index';

/**
 * 
 */
export class ChannelsApi extends runtime.BaseAPI {

    /**
     * List all channels
     */
    async listChannelsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Channel>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/channels`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ChannelFromJSON));
    }

    /**
     * List all channels
     */
    async listChannels(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Channel>> {
        const response = await this.listChannelsRaw(initOverrides);
        return await response.value();
    }

}
