#!/bin/sh

# Purpose: check conventional commits for those not pushed
# Usage: make this script the git pre-push hook
# Dependencies: cocogitto
# Date: 2025-09-02
# Author: Yusong

set -e

# Check commit messages that haven't been pushed.
if ! cog check origin/HEAD..HEAD >/dev/null 2>&1; then
  echo "Error: Commit message(s) violates conventional commits."
  cog check origin/HEAD..HEAD
  exit 1
fi
