#!/bin/sh

# Purpose: check typos in all files excluding ./.git
# Usage: make this script the git pre-commit hook
# Dependencies: typos
# Date: 2025-09-02
# Author: Yusong

set -e

# Check spelling.
typos --hidden --exclude .git --format brief
