name: Cleanup GHCR
on:
  workflow_dispatch:
  schedule:
    # Runs every Saturday at 05:15.
    - cron: "15 5 * * 6"

jobs:
  delete-wt-rest-api:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v6
      - name: Cleanup container images in ghcr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          PACKAGE_NAME: wt-rest-api
          ORG_OR_USER: user
        run: bash ./scripts/cleanup-ghcr.sh

  delete-wt-websocket:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v6
      - name: Cleanup container images in ghcr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          PACKAGE_NAME: wt-websocket
          ORG_OR_USER: user
        run: bash ./scripts/cleanup-ghcr.sh
