name: Build and deploy frontend

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: build wt-webapp and deploy on Cloudflare Pages
    environment:
      name: wt-webapp
      url: ${{ steps.deployment.outputs.deployment-url }}
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
      - name: Build frontend app
        shell: nix shell nixpkgs#bun --quiet --command bash {0}
        run: |
          bun install --cwd wt-webapp
          bun run --cwd wt-webapp build
      - name: Deploy on Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        id: deployment
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN_PAGES }}
          command: |
            pages deploy ./wt-webapp/dist/ --project-name=walkie-talkie
