name: Build and deploy frontend

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: build wt-webapp and deploy on Cloudflare Pages
    environment:
      name: wt-webapp
    permissions:
      contents: read
      deployments: write
    defaults:
      run:
        working-directory: ./wt-webapp
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
      - name: Build frontend app
        shell: nix shell nixpkgs#bun --quiet --command bash {0}
        run: |
          bun install
          bun run build
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Deploy on Cloudflare Workers
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN_PAGES }}
        run: npx wrangler deploy
